### PR TITLE
inserttable(): test for errors and return the number of tuples as a string

### PR DESCRIPTION
**Pull request by justinpryzby**
https://www.postgresql.org/docs/current/libpq-copy.html#LIBPQ-PQPUTCOPYEND

github #72

### CODE REVIEW

**Comment by justinpryzby** [comment]
On Thu, Jun 23, 2022 at 08:01:05AM -0700, Christoph Zwerschke wrote:
> Shouldn't we better return the number of inserted rows as an int?

I returned a string for consistency with db.query()

> Also, can it ever happen that this number is smaller than the number of passed rows (the variable n) when the result status was PGRES_COMMAND_OK? If not, then this number would not be interesting to the caller. Instead we could check for equality and raise some kind of internal error if it differs. That way that caller would not have the burden of checking the return value but can be sure that everything was ok if no error was raised.

Can't it happen with triggers ?

Anyway, I see pygres as a thin layer on top of libpq, so it makes sense to me
to expose whatever libpq returns.  That also avoids doing the wrong thing if
postgres behavior changes in the future.

postgres=# CREATE TABLE t(j int, i serial primary key);
postgres=# CREATE OR REPLACE FUNCTION fnull() RETURNS trigger LANGUAGE plpgsql AS $$ begin RETURN null; END $$;
postgres=# CREATE TRIGGER x BEFORE INSERT ON t FOR EACH ROW EXECUTE FUNCTION fnull();
postgres=# COPY t(i) FROM stdin;
>> 1
>> 2
>> COPY 0

**Comment by Cito** [comment]
> Can't it happen with triggers ?

Yes, you're totally right, you can suppress insertion with a trigger returnin a null value, as you demonstrated. This could even happen conditionally so that it would not always return 0. (Maybe I will add this as another test as well). So yes, I agree, returning that number makes sense. And as you said, it's also the output of the copy command.

> I returned a string for consistency with db.query()

Ok, I already guessed so. Actually db.query() returning a string is an ugly workaround to distinguish it from an inserted OID which is returned as an int. However, I think we will drop OID support in the next major version (since it is not supported by Postgres any more), and that would be an opportunity to do some clean-up of the API and e.g. let db.query() always return an int. But we can do this already here since this is a new functionality.

**Comment by justinpryzby** [comment]
On Thu, Jun 23, 2022 at 08:01:05AM -0700, Christoph Zwerschke wrote:
> Shouldn't we better return the number of inserted rows as an int?

On Thu, Jun 23, 2022 at 11:37:06AM -0700, Christoph Zwerschke wrote:
> > I returned a string for consistency with db.query()
> 
> Ok, I already guessed so. Actually db.query() returning a string is an ugly workaround to distinguish it from an inserted OID which is returned as an int. However, I think we will drop OID support in the next major version (since it is not supported by Postgres any more), and that would be an opportunity to do some clean-up of the API and e.g. let db.query() always return an int. But we can do this already here since this is a new functionality.

I had already written:

><><>snip<><>
Maybe you're right - db.query() supports SELECT/DML/DDL commands, so it needs
to support those.

But inserttable() only needs to support COPY, so it can return an integer.

BTW, db.query() returns "number of affected rows" as a string to avoid
ambiguity with the "insert one row and return its OID as an integer" case.
But "CREATE WITH OIDs" hasn't been supported since v12, so maybe in the next
major release, db.query() should return "number of affected rows" as integers,
rather than OIDs.
><><>snip<><>

BUT, actually:

Pygres is client software, and libpq still supports PQoidValue (), and can
connect to server versions going back decades (?), so maybe the "return OID"
should stay.  But - maybe - integers should be used for the more common use
case of "rows affected", and OIDs can be a string, or something else...

-- 
Justin

**Comment by Cito** [comment]
> Pygres is client software, and libpq still supports PQoidValue (), and can connect to server versions going back decades (?),

Yes, though people should not do it because these server versions contain security vulnerabilities that are not patchable when they are out of support. Postgres 11 (the last version with OID) will reach EOL 2023-11. We will release bug and security fixes for the current major version of PyGres at least until then, but probably longer. In the next major major version we should really modernize and remove support for old Postgres and Python versions, including Python 2, which will simplify the C code a lot.

**Review by Cito — APPROVED** [review]

**Pull request merged**
